### ISSUE TITLE
请问如何部署一个和你一样的博客？包括博客系统和主题？

### ISSUE THREAD

**Issue by Rugel** [kuso-kodo/kuso-kodo.github.io#1]

**Comment by name1e5s** [comment]
我这个博客使用的是 [Hexo](https://hexo.io/) 进行部署的。使用的主题是 [maupassant-hexo](https://github.com/tufu9441/maupassant-hexo)。相关的安装说明可以在对应项目的官网或 README 文档中找到。

**Comment by Rugel** [comment]
感谢
